# vim: ts=2 sw=2 ai paste

---
- hosts: all
  become: true
  vars:
    phy_disk: '/dev/sda'
    phy_part: 1
    lvm_volgrp: 'glusterVol'
    lvm_lvol_varlog: 'varloglv'
    lvm_lvol_varlibdocker: 'varlibdockerlv'    
    mount_point: '/data/glusterfs/bricks/brick1/'


  tasks:

  #- name: partition the disk for lvm
    #parted:
      #device: '{{ phy_disk }}'
      #number: '{{ phy_part }}'
      #flags: [ lvm ]
      #state: present
    #register: phy_diskname
    #tags: disk

#  - name: setup volume group
#    lvg:
#      vg: '{{ lvm_volgrp }}'
#      pvs: '{{ phy_disk }}{{ phy_part}}'
#      state: present
#    register: setup_lvg
#    tags: disk

  - name: setup logical volume for /var/log
    lvol:
      lv: '{{ lvm_lvol_varlog }}'
      vg: '{{ lvm_volgrp }}'
      size: 5G
    register: setup_lvol
 #   when: setup_lvg.changed == true
    tags: disk

  - name: setup logical volume for /var/lib/docker
    lvol:
      lv: '{{ lvm_lvol_varlibdocker }}'
      vg: '{{ lvm_volgrp }}'
      size: 20G
    register: setup_lvol
 #   when: setup_lvg.changed == true
    tags: disk



  - name: create ext4 filesystems
    filesystem:
      fstype: ext4
      dev: '/dev/{{ lvm_volgrp }}/{{ item }}'
    #when: setup_lvol.changed == true
    with_items:
      - '{{ lvm_lvol_varlog }}'
      - '{{ lvm_lvol_varlibdocker }}'
    tags: disk

  - name: create /var/lib/docker
    file:
      path: '/var/lib/docker'
      state: present

  - name: mount /var/lib/docker
    mount:
      path: '/var/lib/docker'
      src: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol_varlibdocker }}'
      fstype: ext4
      state: mounted
    tags: disk 

  - name: mount temporaryt mount for /var/log
    mount:
      path: '/tmp'
      src: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol_varlog }}'
      fstype: ext4
      state: mounted
    tags: disk       
  # - copy:
  #     src: /var/log/
  #     dest: /mnt
  #     remote_src: yes
- synchronize:
    src: /var/log
    dest: /mnt
  delegate_to: {{ inventory_host }}

  - name: delete everything in /var/log
    file:
      path: '/var/log'
      state: absent

  - name: unmount temporary mount
    mount:
      path: '/tmp'
      src: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol_varlog }}'
      fstype: ext4
      state: umounted
    tags: disk

  - name: mount /var/log on proper disk
    mount:
      path: '/var/log'
      src: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol_varlog }}'
      fstype: ext4
      state: mounted
    tags: disk                
