# vim: ts=2 sw=2 ai paste

---
- hosts: all
  become: true
  vars:
    phy_disk: '/dev/sda'
    phy_part: 1
    lvm_volgrp: 'glusterVol'
    lvm_lvol: 'brick1'
    mount_point: '/data/glusterfs/bricks/brick1/'
    client_mount_point: '/data'
    fs_volume_name: 'k8s_vol1'

  tasks:

  - name: partition the disk for lvm
    parted:
      device: '{{ phy_disk }}'
      number: 1
      flags: [ lvm ]
      state: present
    register: phy_diskname
    tags: disk

  - name: setup volume group
    lvg:
      vg: '{{ lvm_volgrp }}'
      pvs: '{{ phy_disk }}{{ phy_part}}'
      state: present
    register: setup_lvg
    tags: disk

  - name: setup logical volume
    lvol:
      lv: '{{ lvm_lvol }}'
      vg: '{{ lvm_volgrp }}'
      size: 50%FREE
    register: setup_lvol
    when: setup_lvg.changed == true
    tags: disk

  - name: create mountpoint directories
    file:
      path: '{{ mount_point }}'
      state: directory
      mode: 0755
    tags: disk

  - name: create xfs filesystems
    filesystem:
      fstype: xfs
      dev: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol }}'
    #when: setup_lvol.changed == true
    tags: disk

  - name: setup mount
    mount:
      path: '{{ mount_point }}'
      src: '/dev/{{ lvm_volgrp }}/{{ lvm_lvol }}'
      fstype: xfs
      state: mounted
    tags: disk

##################disk setup completed #####

#### Install gluster packages
  - name: add apt repo for gluster
    apt_repository:
      repo: ppa:gluster/glusterfs-4.0
      state: present
    tags: gluster_install      

  - name: Install gluster packages
    apt:
      name: glusterfs-server
      state: latest
      update_cache: yes      
    tags: gluster_install

  - name: enable glusterd service
    systemd:
      name: glusterfs-server.service
      enabled: yes
      daemon_reload: yes
      state: started
    tags: gluster_install

  - name: ensure {{ fs_volume_name }} directory exists within brick
    file:
      path: '{{ mount_point }}/{{ fs_volume_name }}'
      state: directory
      mode: 0755
    tags: gluster_install

  - name: create gluster volume
    gluster_volume:
      name: '{{ fs_volume_name }}'
      bricks: '{{ mount_point }}{{ fs_volume_name }}'
      arbiters: 0
      replicas: 3
      state: present
      rebalance: yes
      cluster:
        - k8s1
        - k8s2
        - k8s3
    run_once: true
    register: glusterfs_setup
    tags: gluster_install

  - name: create clientmountpoint for Gluster volume
    file:
      path: '{{ client_mount_point}}/{{ fs_volume_name }}'
      state: present
    tags: gluster_install

  - name: tune gluster volume
    gluster_volume:
    state: present
    name: '{{ fs_volume_name }}'
    options:
      { network.ping-timeout 20,
        performance.cache-size 32MB
      }
    run_once: true 
    tags: gluster_conf    
    tags: gluster_install
