# vim: ts=2 sw=2 ai paste

---
- hosts: all
  become: true
  vars:
    cluster_members:
      - k8s1
      - k8s2
      - k8s3
    pod_network_cidr: '10.243.0/16'

  tasks:

  - name: Install prereq packages
    apt:
      name: {{ item }}
      state: latest
      update_cache: yes
      with_items:
        -  apt-transport-https     
    tags: kubernetes 

  - name: add google apt key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    tags: kubernetes      

  - name: add apt repo for kubernetes
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
    tags: kubernetes

  - name: Install kubeadm and prereq packages
    apt:
      name: kudeadm
      state: latest
      update_cache: yes      
    tags: kubernetes

  - name: Initialize kubernetes
    command: kubeadm init --pod-network-cidr {{ pod_network_cidr }}
    run_once:
    register: kubeadm_output
    tags: kubernetes

  - name: show kubeadm output
    debug:
      var: kubeadm_output.stdout

