---

  - name: enforce log file compression
    replace:
      dest: /etc/logrotate.conf
      regexp: "^#compress"
      replace: "compress"
    tags: syslog

  - name: add bash history configuration
    template:
      src: templates/etc/profile.d/bash-history.sh
      dest: /etc/profile.d/bash-history.sh
      owner: root
      group: root
      mode: 0644
    tags: bash
